### ISSUE TITLE
Keep original copyright notice

### ISSUE THREAD

**Issue by hukkinj1** [linfeng-crypto/cryptopy#1]
Hi!

It seems to me like the code in this repository is based on https://github.com/hukkinj1/cosmospy

I'm glad you found the repository useful. It would be great however if you kept the original copyright notice in place (and I'm under the impression that the MIT license requires this).

**Comment by tomtau** [comment]
hi @hukkinj1 -- thanks for your great work!
this repo is @linfeng-crypto 's personal one, so I can't modify it, but I've added a NOTICE file in this forked repo: https://github.com/crypto-com/chainlibpy/blob/master/NOTICE and added information regarding the original copyright notice in relevant places, e.g. https://github.com/crypto-com/chainlibpy/blob/master/chainlibpy/_transaction.py#L1
feel free to open a PR on the forked repo if anything is missing.

**Comment by hukkinj1** [comment]
Hi @tomtau ,
that looks good!

@linfeng-crypto That, however, doesn't make this particular fork any less bound to the license so I'm a bit confused why this issue was closed?
